spring.application.name=thymeleaf

# ==========================================
# Configuración de PostgreSQL
# ==========================================
spring.datasource.url=jdbc:postgresql://190.146.2.119:2345/javeriana_2026
spring.datasource.username=javeriana_2026
spring.datasource.password=#s1E4Abyskq3
spring.datasource.driver-class-name=org.postgresql.Driver

# Dialecto e integración con JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 'none' o 'validate' para proteger la base de datos remota de cambios involuntarios
spring.jpa.hibernate.ddl-auto=none

# Traza de consultas SQL en consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Desactivar la inicialización por scripts locales
spring.sql.init.mode=never